export const questions = [
  { question: 'What is AI?' },
  { question: 'How does AI work?' },
  { question: 'What is machine learning?' },
  { question: 'What is deep learning?' },
  { question: 'What is a neural network?' },
  { question: 'What is natural language processing?' },
  { question: 'How does AI learn?' },
  { question: 'What is supervised learning?' },
  { question: 'What is unsupervised learning?' },
  { question: 'What is reinforcement learning?' },
  { question: 'What is AI used for?' },
  { question: 'How does AI recognize images?' },
  { question: 'What is a chatbot?' },
  { question: 'What is an AI algorithm?' },
  { question: 'What is the difference between AI and ML?' },
  { question: 'What is AI training?' },
  { question: 'Can AI think like humans?' },
  { question: 'What is AI bias?' },
  { question: 'What is AI ethics?' },
  { question: 'How does AI understand speech?' },
  { question: 'What is a Turing Test?' },
  { question: 'How is AI used in robotics?' },
  { question: 'Can AI be creative?' },
  { question: 'What is computer vision?' },
  { question: 'How do AI assistants work?' },
];
